
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cfase2;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int READLINE = 47;
  public static final int EQUALS = 33;
  public static final int PERIOD = 49;
  public static final int doubleConstant = 55;
  public static final int DOUBLE = 4;
  public static final int SEMI = 40;
  public static final int EXCLAM = 37;
  public static final int GREATER = 31;
  public static final int INTERFACE = 11;
  public static final int INT = 3;
  public static final int intConstant = 54;
  public static final int LESS = 29;
  public static final int FOR = 16;
  public static final int MINUS = 25;
  public static final int RCOR = 51;
  public static final int stringConstant = 57;
  public static final int READINTEGER = 45;
  public static final int RPAR = 7;
  public static final int OR = 39;
  public static final int BOOL = 8;
  public static final int COMMA = 6;
  public static final int CLASS = 10;
  public static final int DIV = 27;
  public static final int boolConstant = 56;
  public static final int NEWARRAY = 22;
  public static final int PLUS = 24;
  public static final int LESSEQ = 30;
  public static final int IF = 17;
  public static final int GETBYTE = 52;
  public static final int THIS = 13;
  public static final int SETBYTE = 53;
  public static final int LLLAV = 42;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int NULL = 12;
  public static final int MOD = 28;
  public static final int hexConstant = 58;
  public static final int IDENT = 38;
  public static final int BREAK = 20;
  public static final int VOID = 2;
  public static final int AMPERSONS = 36;
  public static final int TIMES = 26;
  public static final int PARS = 46;
  public static final int EQTO = 34;
  public static final int ELSE = 18;
  public static final int CORS = 41;
  public static final int WHILE = 44;
  public static final int LCOR = 50;
  public static final int EXTENDS = 14;
  public static final int RLLAV = 43;
  public static final int LPAR = 5;
  public static final int GREATEREQ = 32;
  public static final int STRING = 9;
  public static final int MALLOC = 48;
  public static final int IMPLEMENTS = 15;
  public static final int PRINT = 23;
  public static final int NOTEQ = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "DOUBLE",
  "LPAR",
  "COMMA",
  "RPAR",
  "BOOL",
  "STRING",
  "CLASS",
  "INTERFACE",
  "NULL",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LESS",
  "LESSEQ",
  "GREATER",
  "GREATEREQ",
  "EQUALS",
  "EQTO",
  "NOTEQ",
  "AMPERSONS",
  "EXCLAM",
  "IDENT",
  "OR",
  "SEMI",
  "CORS",
  "LLLAV",
  "RLLAV",
  "WHILE",
  "READINTEGER",
  "PARS",
  "READLINE",
  "MALLOC",
  "PERIOD",
  "LCOR",
  "RCOR",
  "GETBYTE",
  "SETBYTE",
  "intConstant",
  "doubleConstant",
  "boolConstant",
  "stringConstant",
  "hexConstant"
  };
}

