/* The following code was generated by JFlex 1.6.1 */

/* Sección de declaraciones de JFlex */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>./Analizadorlexico.flex</tt>
 */
public class AnalizadorLexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\64\2\0\1\65\22\0\1\32\1\51\1\71\2\0\1\50"+
    "\1\53\1\0\1\60\1\61\1\2\1\47\1\50\1\47\1\55\1\1"+
    "\1\66\11\44\1\0\1\50\1\51\1\52\1\51\2\0\1\33\3\70"+
    "\1\40\1\41\5\45\1\42\1\45\1\31\3\45\1\36\1\43\1\35"+
    "\1\37\2\45\1\67\2\45\1\56\1\72\1\57\1\0\1\46\1\0"+
    "\1\21\1\12\1\20\1\6\1\14\1\22\1\17\1\23\1\5\1\45"+
    "\1\30\1\13\1\25\1\7\1\4\1\26\1\45\1\16\1\15\1\10"+
    "\1\11\1\3\1\27\1\24\1\34\1\45\1\62\1\54\1\63\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\16\3\1\4\2\3\1\5\1\2"+
    "\2\1\3\2\2\6\1\5\1\1\1\7\1\0\2\3"+
    "\1\10\22\3\1\0\1\11\2\0\2\7\1\12\1\0"+
    "\1\3\1\10\15\3\1\10\2\3\1\11\1\0\1\13"+
    "\1\14\1\0\2\3\1\15\4\3\1\0\5\3\1\0"+
    "\2\3\1\0\2\3\1\0\1\3\1\0\1\10";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\73\0\261\0\354\0\u0127\0\u0162"+
    "\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\u02ff\0\u033a"+
    "\0\u0375\0\u03b0\0\73\0\u03eb\0\u0426\0\u0461\0\u049c\0\u04d7"+
    "\0\u0512\0\u054d\0\u0588\0\u05c3\0\73\0\u05fe\0\u0639\0\u0674"+
    "\0\u06af\0\u06ea\0\u0725\0\u0760\0\354\0\u079b\0\u07d6\0\u0811"+
    "\0\u084c\0\u0887\0\u08c2\0\u08fd\0\u0938\0\u0973\0\u09ae\0\u09e9"+
    "\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1"+
    "\0\u0bfc\0\u0c37\0\u0c72\0\73\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e"+
    "\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85\0\u0ec0\0\u0efb\0\u0f36"+
    "\0\u0f71\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e"+
    "\0\u1149\0\u1184\0\u1184\0\u0c37\0\73\0\u0ce8\0\u11bf\0\u11fa"+
    "\0\354\0\u1235\0\u1270\0\u12ab\0\u12e6\0\u1321\0\u135c\0\u1397"+
    "\0\u13d2\0\u140d\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f"+
    "\0\u15aa\0\u15e5\0\u1620\0\u165b\0\73";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\6\1\13\1\6\1\14\1\15\1\16\1\6"+
    "\1\17\1\6\1\20\4\6\1\21\1\6\1\22\1\23"+
    "\2\6\1\24\3\6\1\25\2\6\1\26\1\6\1\2"+
    "\2\4\2\27\1\30\1\31\1\4\1\32\1\4\1\33"+
    "\1\4\1\34\1\4\1\35\1\36\1\37\2\6\1\40"+
    "\1\2\74\0\1\41\1\42\73\0\1\6\1\43\25\6"+
    "\1\0\14\6\17\0\3\6\5\0\27\6\1\0\14\6"+
    "\17\0\3\6\5\0\4\6\1\44\12\6\1\45\2\6"+
    "\1\46\4\6\1\0\14\6\17\0\3\6\5\0\1\6"+
    "\1\47\25\6\1\0\14\6\17\0\3\6\5\0\6\6"+
    "\1\50\20\6\1\0\14\6\17\0\3\6\5\0\13\6"+
    "\1\51\4\6\1\52\6\6\1\0\14\6\17\0\3\6"+
    "\5\0\1\6\1\53\11\6\1\54\13\6\1\0\14\6"+
    "\17\0\3\6\5\0\10\6\1\55\10\6\1\56\5\6"+
    "\1\0\14\6\17\0\3\6\5\0\5\6\1\57\21\6"+
    "\1\0\14\6\17\0\3\6\5\0\11\6\1\60\15\6"+
    "\1\0\14\6\17\0\3\6\5\0\10\6\1\61\16\6"+
    "\1\0\14\6\17\0\3\6\5\0\1\6\1\62\14\6"+
    "\1\63\10\6\1\0\14\6\17\0\3\6\5\0\20\6"+
    "\1\64\6\6\1\0\14\6\17\0\3\6\5\0\11\6"+
    "\1\65\15\6\1\0\14\6\17\0\3\6\5\0\27\6"+
    "\1\0\3\6\1\66\10\6\17\0\3\6\5\0\27\6"+
    "\1\0\1\67\13\6\17\0\3\6\16\0\1\70\23\0"+
    "\1\70\3\0\1\26\10\0\1\71\10\0\1\26\56\0"+
    "\1\4\73\0\1\4\73\0\1\4\75\0\1\4\74\0"+
    "\1\4\74\0\1\4\73\0\1\35\22\0\1\70\7\0"+
    "\1\72\13\0\1\70\3\0\1\26\10\0\1\71\10\0"+
    "\1\26\1\72\3\0\71\73\1\0\1\73\64\41\1\74"+
    "\1\75\5\41\2\76\1\77\70\76\3\0\2\6\1\100"+
    "\24\6\1\0\14\6\17\0\3\6\5\0\5\6\1\101"+
    "\21\6\1\0\14\6\17\0\3\6\5\0\23\6\1\102"+
    "\3\6\1\0\14\6\17\0\3\6\5\0\6\6\1\103"+
    "\20\6\1\0\14\6\17\0\3\6\5\0\10\6\1\104"+
    "\16\6\1\0\14\6\17\0\3\6\5\0\6\6\1\105"+
    "\20\6\1\0\14\6\17\0\3\6\5\0\2\6\1\106"+
    "\24\6\1\0\14\6\17\0\3\6\5\0\1\6\1\104"+
    "\25\6\1\0\14\6\17\0\3\6\5\0\11\6\1\107"+
    "\15\6\1\0\14\6\17\0\3\6\5\0\12\6\1\110"+
    "\14\6\1\0\14\6\17\0\3\6\5\0\5\6\1\111"+
    "\21\6\1\0\14\6\17\0\3\6\5\0\13\6\1\112"+
    "\13\6\1\0\14\6\17\0\3\6\5\0\5\6\1\113"+
    "\21\6\1\0\14\6\17\0\3\6\5\0\16\6\1\114"+
    "\10\6\1\0\14\6\17\0\3\6\5\0\13\6\1\45"+
    "\13\6\1\0\14\6\17\0\3\6\5\0\10\6\1\115"+
    "\16\6\1\0\14\6\17\0\3\6\5\0\2\6\1\116"+
    "\24\6\1\0\14\6\17\0\3\6\5\0\24\6\1\117"+
    "\2\6\1\0\14\6\17\0\3\6\5\0\27\6\1\0"+
    "\4\6\1\120\7\6\17\0\3\6\5\0\27\6\1\0"+
    "\7\6\1\121\4\6\17\0\3\6\46\0\1\122\2\0"+
    "\1\123\16\0\1\122\20\0\1\70\23\0\1\70\3\0"+
    "\1\71\21\0\1\71\12\0\1\124\3\0\1\124\1\0"+
    "\1\124\3\0\3\124\10\0\1\124\4\0\2\124\2\0"+
    "\1\124\21\0\1\124\1\0\1\124\2\0\64\73\2\0"+
    "\3\73\1\125\65\0\1\74\6\0\2\126\1\77\71\126"+
    "\1\74\1\77\70\126\3\0\3\6\1\45\23\6\1\0"+
    "\14\6\17\0\3\6\5\0\11\6\1\127\15\6\1\0"+
    "\14\6\17\0\3\6\5\0\10\6\1\130\16\6\1\0"+
    "\14\6\17\0\3\6\5\0\7\6\1\116\17\6\1\0"+
    "\14\6\17\0\3\6\5\0\10\6\1\45\16\6\1\0"+
    "\14\6\17\0\3\6\5\0\11\6\1\131\15\6\1\0"+
    "\14\6\17\0\3\6\5\0\12\6\1\45\14\6\1\0"+
    "\14\6\17\0\3\6\5\0\16\6\1\132\10\6\1\0"+
    "\14\6\17\0\3\6\5\0\11\6\1\45\15\6\1\0"+
    "\14\6\17\0\3\6\5\0\11\6\1\133\15\6\1\0"+
    "\14\6\17\0\3\6\5\0\2\6\1\134\24\6\1\0"+
    "\14\6\17\0\3\6\5\0\6\6\1\135\20\6\1\0"+
    "\14\6\17\0\3\6\5\0\12\6\1\106\14\6\1\0"+
    "\14\6\17\0\3\6\5\0\12\6\1\105\14\6\1\0"+
    "\14\6\17\0\3\6\5\0\10\6\1\110\16\6\1\0"+
    "\14\6\17\0\3\6\5\0\27\6\1\136\14\6\17\0"+
    "\3\6\5\0\27\6\1\0\5\6\1\131\6\6\17\0"+
    "\3\6\5\0\27\6\1\0\10\6\1\120\3\6\17\0"+
    "\3\6\46\0\1\122\21\0\1\122\7\0\13\6\1\137"+
    "\13\6\1\0\14\6\17\0\3\6\5\0\11\6\1\140"+
    "\15\6\1\0\14\6\17\0\3\6\5\0\25\6\1\45"+
    "\1\6\1\0\14\6\17\0\3\6\5\0\4\6\1\141"+
    "\22\6\1\0\14\6\17\0\3\6\5\0\4\6\1\142"+
    "\22\6\1\0\14\6\17\0\3\6\5\0\13\6\1\143"+
    "\13\6\1\0\14\6\17\0\3\6\35\0\1\144\42\0"+
    "\17\6\1\145\7\6\1\0\14\6\17\0\3\6\5\0"+
    "\22\6\1\146\4\6\1\0\14\6\17\0\3\6\5\0"+
    "\3\6\1\106\23\6\1\0\14\6\17\0\3\6\5\0"+
    "\14\6\1\45\12\6\1\0\14\6\17\0\3\6\5\0"+
    "\4\6\1\45\22\6\1\0\14\6\17\0\3\6\20\0"+
    "\1\147\57\0\16\6\1\150\10\6\1\0\14\6\17\0"+
    "\3\6\5\0\11\6\1\151\15\6\1\0\14\6\17\0"+
    "\3\6\20\0\1\152\57\0\15\6\1\110\11\6\1\0"+
    "\14\6\17\0\3\6\5\0\4\6\1\153\22\6\1\0"+
    "\14\6\17\0\3\6\23\0\1\154\54\0\5\6\1\106"+
    "\21\6\1\0\14\6\17\0\3\6\36\0\1\155\36\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5782];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\16\1\1\11\11\1\1\11"+
    "\4\1\1\0\25\1\1\0\1\1\2\0\1\11\2\1"+
    "\1\0\23\1\1\0\1\1\1\11\1\0\7\1\1\0"+
    "\5\1\1\0\2\1\1\0\2\1\1\0\1\1\1\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
 
 /* Código personalizado */
 
 // Se agregó una propiedad para verificar si existen tokens pendientes
 private boolean _existenTokens = false;
 private boolean _existenErrores = false;
 public boolean existenTokens(){
 return this._existenTokens;
 }
public boolean existenError(){
 return this._existenErrores;
 }
 


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
   /* Código que se ejecutará en el constructor de la clase */
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 192) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
     
 /* Código a ejecutar al finalizar el análisis, en este caso cambiaremos el valor de una variable bandera */
 this._existenTokens = false;
 

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public TokenPersonalizado yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Unrecognized char: " + yytext(), yycolumn, yyline);
 this._existenTokens = true;
 
 return t;
            }
          case 14: break;
          case 2: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Simbolo/Operador", yycolumn, yyline);
 this._existenTokens = true;
 return t;
            }
          case 15: break;
          case 3: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Identificador", yycolumn, yyline);
 this._existenTokens = true;
 return t;
            }
          case 16: break;
          case 4: 
            { // Ignorar cuando se ingrese un espacio
            }
          case 17: break;
          case 5: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Constante Entera", yycolumn, yyline);
 this._existenTokens = true;
 return t;
            }
          case 18: break;
          case 6: 
            { /*TokenPersonalizado t = new TokenPersonalizado("Enter", "NUEVA_LINEA");
 this._existenTokens = true;
 return t;*/
            }
          case 19: break;
          case 7: 
            { 
            }
          case 20: break;
          case 8: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Palabra Reservada", yycolumn, yyline);
 this._existenTokens = true;
 return t;
            }
          case 21: break;
          case 9: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Constante Double", yycolumn, yyline);
 this._existenTokens = true;
 return t;
            }
          case 22: break;
          case 10: 
            { TokenPersonalizado t = new TokenPersonalizado("comentario Incompleto", "Error", yycolumn, yyline);
 this._existenTokens = true;
 this._existenErrores = true;
 return t;
            }
          case 23: break;
          case 11: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Constante Hex", yycolumn, yyline);
 this._existenTokens = true;
 return t;
            }
          case 24: break;
          case 12: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Cadena String", yycolumn, yyline);
 this._existenTokens = true;
 return t;
            }
          case 25: break;
          case 13: 
            { TokenPersonalizado t = new TokenPersonalizado(yytext(), "Variable booleana", yycolumn, yyline);
 this._existenTokens = true;
 return t;
            }
          case 26: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
